# Document Clustering and Topic Modeling 

## Contents

* [Part 1: Load Data](#Part-1:-Load-Data)
* [Part 2: Tokenizing and Stemming](#Part-2:-Tokenizing-and-Stemming)
* [Part 3: TF-IDF](#Part-3:-TF-IDF)
* [Part 4: K-means clustering](#Part-4:-K-means-clustering)
* [Part 5: Topic Modeling - Latent Dirichlet Allocation](#Part-5:-Topic-Modeling---Latent-Dirichlet-Allocation)


In [ ]:
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
file = drive.CreateFile({'id':'1UIS6YrBoeIrg6i4qEhXrF-NEK0L3W42_'}) 
file.GetContentFile('data.tsv')  

# Part 1: Load Data

In [ ]:
import numpy as np
import pandas as pd
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
df = pd.read_csv('data.tsv', sep='\t', error_bad_lines=False) #！！

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
b'Skipping line 8704: expected 15 fields, saw 22\nSkipping line 16933: expected 15 fields, saw 22\nSkipping line 23726: expected 15 fields, saw 22\n'
b'Skipping line 85637: expected 15 fields, saw 22\n'
b'Skipping line 132136: expected 15 fields, saw 22\nSkipping line 158070: expected 15 fields, saw 22\nSkipping line 166007: expected 15 fields, saw 22\nSkipping line 171877: expected 15 fields, saw 22\nSkipping line 177756: expected 15 fields, saw 22\nSkipping line 181773: expected 15 fields, saw 22\nSkipping line 191085: expected 15 fields, saw 22\nSkipping line 196273: expected 15 fields, saw 22\nSkipping line 196331: expected 15 fields, saw 22\n'
b'Skipping line 197000: expected 15 fields, saw 22\nSkipping line 197011: expected 15 fields, saw 22\nSkip

In [ ]:
df.head()

marketplace  ...  review_date
0          US  ...   2015-08-31
1          US  ...   2015-08-31
2          US  ...   2015-08-31
3          US  ...   2015-08-31
4          US  ...   2015-08-31

[5 rows x 15 columns]

In [ ]:
# Remove missing value
df.dropna(subset=['review_body'],inplace=True)

In [ ]:
df.reset_index(inplace=True, drop=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960056 entries, 0 to 960055
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   marketplace        960056 non-null  object
 1   customer_id        960056 non-null  int64 
 2   review_id          960056 non-null  object
 3   product_id         960056 non-null  object
 4   product_parent     960056 non-null  int64 
 5   product_title      960054 non-null  object
 6   product_category   960056 non-null  object
 7   star_rating        960056 non-null  int64 
 8   helpful_votes      960056 non-null  int64 
 9   total_votes        960056 non-null  int64 
 10  vine               960056 non-null  object
 11  verified_purchase  960056 non-null  object
 12  review_headline    960049 non-null  object
 13  review_body        960056 non-null  object
 14  review_date        960052 non-null  object
dtypes: int64(5), object(10)
memory usage: 109.9+ MB


In [ ]:
# training data
data = df.loc[:1999, 'review_body'].tolist()

# Part 2: Tokenizing and Stemming

In [ ]:
# Load stopwords and stemmer function from NLTK library.

# Stemming is the process of breaking a word down into its root.
# Stop words are words like "a", "the", or "in" which don't convey significant meaning.

# Use nltk's English stopwords.
stopwords = nltk.corpus.stopwords.words('english') 
stopwords.append("'s") 
stopwords.append("'m")
stopwords.append("br") 
stopwords.append("watch") 

print ("We use " + str(len(stopwords)) + " stop-words from nltk library.")
print (stopwords[:10])

We use 183 stop-words from nltk library.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [ ]:
# Use our defined functions to analyze (i.e. tokenize, stem) our reviews.
from nltk.stem.snowball import SnowballStemmer
# from nltk.stem import WordNetLemmatizer 
stemmer = SnowballStemmer("english")

# tokenization and stemming
def tokenization_and_stemming(text): 
    tokens = []   
    for word in nltk.word_tokenize(text):
        if word.lower() not in stopwords:
            tokens.append(word.lower())

    filtered_tokens = []
    
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if token.isalpha():
            filtered_tokens.append(token)
     
    # stemming
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

# Part 3: TF-IDF

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
# define vectorizer parameters
# TfidfVectorizer will help us to create tf-idf matrix
# max_df : maximum document frequency for the given word
# min_df : minimum document frequency for the given word
# max_features: maximum number of words
# use_idf: if not true, we only calculate tf
# stop_words : built-in stop words
# tokenizer: how to tokenize the document
# ngram_range: (min_value, max_value), eg. (1, 3) means the result will include 1-gram, 2-gram, 3-gram
tfidf_model = TfidfVectorizer(max_df=0.99, max_features=1000,
                                 min_df=0.01, stop_words='english',
                                 use_idf=True, tokenizer=tokenization_and_stemming, ngram_range=(1,1))

tfidf_matrix = tfidf_model.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix.shape[0]) + \
      " reviews and " + str(tfidf_matrix.shape[1]) + " terms.")

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  % sorted(inconsistent)


In total, there are 2000 reviews and 246 terms.


In [13]:
tfidf_matrix

<2000x246 sparse matrix of type '<class 'numpy.float64'>'
	with 14532 stored elements in Compressed Sparse Row format>

In [14]:
# Save the terms identified by TF-IDF. 
# words
tf_selected_words = tfidf_model.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [15]:
# print out words
tf_selected_words

['abl',
 'absolut',
 'accur',
 'actual',
 'add',
 'adjust',
 'alarm',
 'alreadi',
 'alway',
 'amaz',
 'amazon',
 'anoth',
 'appear',
 'arriv',
 'attract',
 'automat',
 'awesom',
 'bad',
 'band',
 'batteri',
 'beauti',
 'best',
 'better',
 'big',
 'bit',
 'black',
 'blue',
 'bought',
 'box',
 'brand',
 'break',
 'bright',
 'broke',
 'broken',
 'button',
 'buy',
 'ca',
 'came',
 'case',
 'casio',
 'chang',
 'cheap',
 'check',
 'clasp',
 'classi',
 'clear',
 'clock',
 'collect',
 'color',
 'come',
 'comfort',
 'compliment',
 'cool',
 'cost',
 'coupl',
 'crown',
 'crystal',
 'cute',
 'dark',
 'date',
 'daughter',
 'day',
 'deal',
 'definit',
 'deliveri',
 'design',
 'dial',
 'differ',
 'digit',
 'disappoint',
 'display',
 'dress',
 'durabl',
 'easi',
 'easili',
 'eleg',
 'end',
 'everi',
 'everyday',
 'everyth',
 'exact',
 'excel',
 'expect',
 'expens',
 'extrem',
 'face',
 'fact',
 'far',
 'fast',
 'featur',
 'feel',
 'fell',
 'figur',
 'fine',
 'finish',
 'fit',
 'function',
 'gift',
 'g

# Part 4: K-means clustering

In [ ]:
# k-means clustering
from sklearn.cluster import KMeans

# set K
num_clusters = 5

# number of clusters
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)

clusters = km.labels_.tolist()

## 4.1. Analyze K-means Result

In [17]:
# k-means clustering
from sklearn.cluster import KMeans
num_clusters = 10
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)
clusters = km.labels_.tolist()

# create DataFrame films from all of the input files.
product = { 'review': df[:2000].review_body, 'cluster': clusters}
frame = pd.DataFrame(product, columns = ['review', 'cluster'])

In [ ]:
frame.head(10)

review  cluster
0  Absolutely love this watch! Get compliments al...        2
1       I love this watch it keeps time wonderfully.        2
2                                          Scratches        3
3  It works well on me. However, I found cheaper ...        3
4  Beautiful watch face.  The band looks nice all...        3
5  i love this watch for my purpose, about the pe...        2
6  for my wife and she loved it, looks great and ...        4
7  I was about to buy this thinking it was a Swis...        3
8  Watch is perfect. Rugged with the metal &#34;B...        4
9  Great quality and build.<br />The motors are r...        3

In [18]:
print ("Number of reviews included in each cluster:")
frame['cluster'].value_counts().to_frame()

Number of reviews included in each cluster:


cluster
1      859
6      271
8      148
5      128
4      122
9      110
2      110
7      107
3       93
0       52

In [19]:
km.cluster_centers_

array([[0.        , 0.        , 0.        , ..., 0.        , 0.01220659,
        0.00641191],
       [0.00657573, 0.00186084, 0.00641657, ..., 0.01054739, 0.02378945,
        0.02100651],
       [0.00277647, 0.01823814, 0.00395462, ..., 0.00914958, 0.00288338,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.03466263, 0.        , ..., 0.00600754, 0.00596094,
        0.        ],
       [0.        , 0.00493754, 0.00282315, ..., 0.        , 0.02867561,
        0.00776159]])

In [21]:
print ("<Document clustering result by K-means>")

#km.cluster_centers_ denotes the importances of each items in centroid.
#We need to sort it in decreasing-order and get the top k items.
order_centroids = km.cluster_centers_.argsort()[:, ::-1] 

Cluster_keywords_summary = {}
for i in range(num_clusters):
    print ("Cluster " + str(i) + " words:", end='')
    Cluster_keywords_summary[i] = []
    for ind in order_centroids[i, :6]: #replace 6 with n words per cluster
        Cluster_keywords_summary[i].append(tf_selected_words[ind])
        print (tf_selected_words[ind] + ",", end='')
    print ()
    
    cluster_reviews = frame[frame.cluster==i].review.tolist()
    print ("Cluster " + str(i) + " reviews (" + str(len(cluster_reviews)) + " reviews): ")
    print (", ".join(cluster_reviews))
    print ()

<Document clustering result by K-means>
Cluster 0 words:excel,product,price,fast,good,qualiti,
Cluster 0 reviews (52 reviews): 
excelent product, Excellent product and seller very good service, Excelent for the price., I am extremely pleased with the product.  Excellent watch!, Very nice watch. I get compliments all the time and everyone asks where I got it. This is an excellent watch for business/formal types of gigs that doesn't break the bank. Not heavy on the wrist., Excellent Product, competitive price and quick delivery., Great item... excellent price, My husband loves it!  Excellent product!, excellent watch, Excellent quality. Solid. Would highly recommend., Excellent. My son loves it. He wants to swim with it, so we are yet to pass this test!, excellent, Excelent for the price., Excellent product!, Excelent..., Excellent quality and very fast shipping thank you., Excelent!, Excellent quality and very fast shipping thank you., Excellent product!...great deal!, Excellent feeling

# Part 5: Topic Modeling - Latent Dirichlet Allocation

In [22]:
# Use LDA for clustering
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=5)

In [23]:
# document topic matrix for tfidf_matrix_lda
lda_output = lda.fit_transform(tfidf_matrix)
print(lda_output.shape)
print(lda_output)

(2000, 5)
[[0.05980632 0.06081427 0.75834744 0.06057401 0.06045795]
 [0.08437639 0.08382157 0.6571357  0.0870328  0.08763354]
 [0.1000023  0.59867746 0.10100938 0.10000275 0.10030811]
 ...
 [0.06713775 0.08077364 0.06934641 0.06511992 0.71762227]
 [0.10145631 0.10011517 0.59729085 0.10042156 0.10071611]
 [0.2        0.2        0.2        0.2        0.2       ]]


In [24]:
# topics and words matrix
topic_word = lda.components_
print(topic_word.shape)
print(topic_word)

(5, 246)
[[ 0.21096457  0.20164186  0.20118794 ...  0.20777257 20.44062984
   2.10727747]
 [ 6.26310212  0.21167343  0.27613424 ... 10.26791412  0.20204211
   0.28066742]
 [ 0.21790952 11.9871265   1.8068008  ...  0.20263932  7.15770791
   2.13272371]
 [ 0.20626269  0.20207949  3.83015448 ...  3.08791172  1.03337633
  19.98779841]
 [ 3.03120777  0.20310709  2.99350761 ...  0.20147352  6.03680166
   0.20218647]]


In [25]:
# column names
topic_names = ["Topic" + str(i) for i in range(lda.n_components)]

# index names
doc_names = ["Doc" + str(i) for i in range(len(data))]

df_document_topic = pd.DataFrame(np.round(lda_output, 2), columns=topic_names, index=doc_names)

# get dominant topic for each document
topic = np.argmax(df_document_topic.values, axis=1)
df_document_topic['topic'] = topic

df_document_topic.head(10)

Topic0  Topic1  Topic2  Topic3  Topic4  topic
Doc0    0.06    0.06    0.76    0.06    0.06      2
Doc1    0.08    0.08    0.66    0.09    0.09      2
Doc2    0.10    0.60    0.10    0.10    0.10      1
Doc3    0.46    0.06    0.06    0.36    0.06      0
Doc4    0.42    0.04    0.46    0.04    0.04      2
Doc5    0.07    0.69    0.08    0.08    0.08      1
Doc6    0.06    0.53    0.07    0.06    0.28      1
Doc7    0.06    0.06    0.06    0.75    0.06      3
Doc8    0.05    0.23    0.63    0.05    0.05      2
Doc9    0.06    0.77    0.06    0.06    0.06      1

In [26]:
df_document_topic['topic'].value_counts().to_frame()

topic
2    583
0    408
3    403
1    315
4    291

In [29]:
print(lda.components_)
df_topic_words = pd.DataFrame(lda.components_)
df_topic_words.columns = tfidf_model.get_feature_names()
df_topic_words.index = topic_names
df_topic_words.head()

[[ 0.21096457  0.20164186  0.20118794 ...  0.20777257 20.44062984
   2.10727747]
 [ 6.26310212  0.21167343  0.27613424 ... 10.26791412  0.20204211
   0.28066742]
 [ 0.21790952 11.9871265   1.8068008  ...  0.20263932  7.15770791
   2.13272371]
 [ 0.20626269  0.20207949  3.83015448 ...  3.08791172  1.03337633
  19.98779841]
 [ 3.03120777  0.20310709  2.99350761 ...  0.20147352  6.03680166
   0.20218647]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


abl    absolut     accur  ...      worth      wrist       year
Topic0  0.210965   0.201642  0.201188  ...   0.207773  20.440630   2.107277
Topic1  6.263102   0.211673  0.276134  ...  10.267914   0.202042   0.280667
Topic2  0.217910  11.987127  1.806801  ...   0.202639   7.157708   2.132724
Topic3  0.206263   0.202079  3.830154  ...   3.087912   1.033376  19.987798
Topic4  3.031208   0.203107  2.993508  ...   0.201474   6.036802   0.202186

[5 rows x 246 columns]

In [30]:
# print top n keywords for each topic
def print_topic_words(tfidf_model, lda_model, n_words):
    words = np.array(tfidf_model.get_feature_names())
    topic_words = []
    for topic_words_weights in lda_model.components_:
        top_words = topic_words_weights.argsort()[::-1][:n_words]
        topic_words.append(words.take(top_words))
    return topic_words

topic_keywords = print_topic_words(tfidf_model=tfidf_model, lda_model=lda, n_words=15)        

df_topic_words = pd.DataFrame(topic_keywords)
df_topic_words.columns = ['Word '+str(i) for i in range(df_topic_words.shape[1])]
df_topic_words.index = ['Topic '+str(i) for i in range(df_topic_words.shape[0])]
df_topic_words

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Word 0   Word 1   Word 2   Word 3  ... Word 11  Word 12 Word 13  Word 14
Topic 0    good     look     band     face  ...    link  invicta   littl     easi
Topic 1    nice    great    price   expect  ...    deal     band      ok  everyth
Topic 2    love     like     gift     look  ...    feel     time    amaz     blue
Topic 3    work    excel  product  batteri  ...    stop     wear    week   replac
Topic 4  beauti  perfect    exact     time  ...    want     item    band    pleas

[5 rows x 15 columns]